/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package informacionenmultiplesventanas;

import javax.swing.JOptionPane;

/**
 *
 * @author aser
 */
public class vistaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(vistaPrincipal.class.getName());
    //instancia de la clase, en donde se indica el tamaño del array
    claseCliente cliente = new claseCliente(5);
    
    //Getters para mandar a la otra vista
    public String getNombre(int pos){
        return cliente.getNombreCliente(pos);
    }
    
    public String getId(int pos){
      return cliente.getIdCliente(pos);  
    }
    
    public int getDinero(int pos){
      return cliente.getDineroCliente(pos);  
    }
    
    
    /**
     * Creates new form vistaPrincipal
     */
    public vistaPrincipal() {
        initComponents();
        btnVista2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg1 = new javax.swing.JPanel();
        txt1 = new javax.swing.JLabel();
        inputNombreCliente = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txt2 = new javax.swing.JLabel();
        inputIdCliente = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        inputDineroCliente = new javax.swing.JTextField();
        txt3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txt4 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnVista2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg1.setForeground(new java.awt.Color(255, 255, 255));

        txt1.setFont(new java.awt.Font("Ubuntu Sans", 1, 24)); // NOI18N
        txt1.setText("Nombre de el cliente:");

        inputNombreCliente.setFont(new java.awt.Font("Ubuntu Sans", 1, 24)); // NOI18N

        txt2.setFont(new java.awt.Font("Ubuntu Sans", 1, 24)); // NOI18N
        txt2.setText("ID del cliente:");

        inputIdCliente.setFont(new java.awt.Font("Ubuntu Sans", 1, 24)); // NOI18N

        inputDineroCliente.setFont(new java.awt.Font("Ubuntu Sans", 1, 24)); // NOI18N

        txt3.setFont(new java.awt.Font("Ubuntu Sans", 1, 24)); // NOI18N
        txt3.setText("Dinero del cliente:");

        txt4.setFont(new java.awt.Font("Ubuntu Sans", 1, 24)); // NOI18N
        txt4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt4.setText("Sistema bancario");

        btnGuardar.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnLimpiar.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        btnLimpiar.setText("Limpiar");

        btnVista2.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        btnVista2.setText("Vista2");
        btnVista2.addActionListener(this::btnVista2ActionPerformed);

        javax.swing.GroupLayout bg1Layout = new javax.swing.GroupLayout(bg1);
        bg1.setLayout(bg1Layout);
        bg1Layout.setHorizontalGroup(
            bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg1Layout.createSequentialGroup()
                .addGroup(bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bg1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2)
                            .addGroup(bg1Layout.createSequentialGroup()
                                .addComponent(txt2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputIdCliente))
                            .addGroup(bg1Layout.createSequentialGroup()
                                .addComponent(txt3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputDineroCliente))
                            .addComponent(jSeparator3)
                            .addGroup(bg1Layout.createSequentialGroup()
                                .addGroup(bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bg1Layout.createSequentialGroup()
                                        .addComponent(txt1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(inputNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(bg1Layout.createSequentialGroup()
                                        .addComponent(btnGuardar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnLimpiar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnVista2)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        bg1Layout.setVerticalGroup(
            bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputDineroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnVista2))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int posCliente = 0;
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
        //validacion si los campos están llenos
        if (inputNombreCliente.getText().isEmpty() || inputIdCliente.getText().isEmpty() || inputDineroCliente.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Debe llenar todos los campos");
        }
        //validacion si hay espacio en el array
        if (posCliente <= cliente.getTamCliente()){
            
            String nombreCliente = inputNombreCliente.getText();
            String idCliente = inputIdCliente.getText();
            int dineroCliente = Integer.parseInt(inputIdCliente.getText());
        
            cliente.setDatosCliente(posCliente, nombreCliente, idCliente, dineroCliente);
            posCliente++;
        
            JOptionPane.showMessageDialog(rootPane, "Cliente ingresado exitosamente");
            btnVista2.setVisible(true);
            
        } else{
            JOptionPane.showMessageDialog(rootPane, "No hay espacio disponible en el array cliente");
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnVista2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVista2ActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        
        vistaSecundaria ventana2 = new vistaSecundaria();
        ventana2.setVisible(true);
        
    }//GEN-LAST:event_btnVista2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new vistaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg1;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnVista2;
    private javax.swing.JTextField inputDineroCliente;
    private javax.swing.JTextField inputIdCliente;
    private javax.swing.JTextField inputNombreCliente;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt2;
    private javax.swing.JLabel txt3;
    private javax.swing.JLabel txt4;
    // End of variables declaration//GEN-END:variables
}
