package notas;

import javax.swing.JOptionPane;
import notas.clases.claseEstudiante;
import notas.clases.claseMateria;
import notas.clases.claseMatricula;

public class vista extends javax.swing.JFrame {
    claseEstudiante estudiante = new claseEstudiante();
    claseMateria materia = new claseMateria();
    claseMatricula  matricula = new claseMatricula();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(vista.class.getName());

    /**
     * Creates new form vista
     */
    public vista() {
        initComponents();
        txt14.setVisible(false);
        txt15.setVisible(false);
        txt16.setVisible(false);
        
        inputNota1Matricula.setVisible(false);
        inputNota2Matricula.setVisible(false);
        inputNota3Matricula.setVisible(false);
        
        btnGuardarInfoMatricula.setVisible(false);
        btnCargarNotasMatricula.setVisible(false);
        btnGuardarMatricula.setVisible(false);
        
        inputPeriodoAcademicoMatricula.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txt1 = new javax.swing.JLabel();
        inputIdEstudiante = new javax.swing.JTextField();
        txt2 = new javax.swing.JLabel();
        inputNombreEstudiante = new javax.swing.JTextField();
        txt3 = new javax.swing.JLabel();
        comboBoxEdadEstudiante = new javax.swing.JComboBox<>();
        txt4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        txt5 = new javax.swing.JLabel();
        inputCorreoEstudiante = new javax.swing.JTextField();
        btnGuardarEstudiante = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txt6 = new javax.swing.JLabel();
        inputCodigoMateria = new javax.swing.JTextField();
        txt7 = new javax.swing.JLabel();
        inputNombreMateria = new javax.swing.JTextField();
        txt8 = new javax.swing.JLabel();
        comboBoxNumeroCreditoMateria = new javax.swing.JComboBox<>();
        txt9 = new javax.swing.JLabel();
        comboBoxSemestreMateria = new javax.swing.JComboBox<>();
        comboBoxCarreraMateria = new javax.swing.JComboBox<>();
        txt10 = new javax.swing.JLabel();
        btnGuardarMateria = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txt11 = new javax.swing.JLabel();
        outputIdEstudianteMatricula = new javax.swing.JTextField();
        txt12 = new javax.swing.JLabel();
        outputCodigoMateriaMatricula = new javax.swing.JTextField();
        inputPeriodoAcademicoMatricula = new javax.swing.JTextField();
        txt13 = new javax.swing.JLabel();
        txt14 = new javax.swing.JLabel();
        inputNota1Matricula = new javax.swing.JTextField();
        txt15 = new javax.swing.JLabel();
        inputNota2Matricula = new javax.swing.JTextField();
        txt16 = new javax.swing.JLabel();
        inputNota3Matricula = new javax.swing.JTextField();
        btnCargarDatosMatricula = new javax.swing.JButton();
        btnGuardarInfoMatricula = new javax.swing.JButton();
        btnCargarNotasMatricula = new javax.swing.JButton();
        btnGuardarMatricula = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt1.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt1.setText("ID");

        txt2.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt2.setText("Nombre");

        txt3.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt3.setText("Edad");

        comboBoxEdadEstudiante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "17", "18", "19", "20", "21", "22", "23", "24" }));

        txt4.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt4.setText("Sexo");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Masculino");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Femenino");

        txt5.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt5.setText("Correo");

        btnGuardarEstudiante.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        btnGuardarEstudiante.setText("Guardar");
        btnGuardarEstudiante.addActionListener(this::btnGuardarEstudianteActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txt1)
                            .addGap(18, 18, 18)
                            .addComponent(inputIdEstudiante))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txt2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(inputNombreEstudiante))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txt3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(comboBoxEdadEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txt4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jRadioButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jRadioButton2))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txt5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(inputCorreoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnGuardarEstudiante))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt1)
                    .addComponent(inputIdEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt2)
                    .addComponent(inputNombreEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt3)
                    .addComponent(comboBoxEdadEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt4)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt5)
                    .addComponent(inputCorreoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarEstudiante)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Estudiante", jPanel1);

        txt6.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt6.setText("Código materia");

        txt7.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt7.setText("Nombre");

        txt8.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt8.setText("N. credito");

        comboBoxNumeroCreditoMateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "1", "2", "3", "4", "5", "6" }));

        txt9.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt9.setText("Semestre");

        comboBoxSemestreMateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        comboBoxCarreraMateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "filosofia", "trabajo social", "diseño grafico" }));

        txt10.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt10.setText("Carrera");

        btnGuardarMateria.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        btnGuardarMateria.setText("Guardar");
        btnGuardarMateria.addActionListener(this::btnGuardarMateriaActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt6)
                                .addGap(18, 18, 18)
                                .addComponent(inputCodigoMateria, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt7)
                                .addGap(18, 18, 18)
                                .addComponent(inputNombreMateria))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txt8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboBoxNumeroCreditoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txt10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboBoxCarreraMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(254, 254, 254))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnGuardarMateria)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxSemestreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt6)
                    .addComponent(inputCodigoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt7)
                    .addComponent(inputNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt8)
                    .addComponent(comboBoxNumeroCreditoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt9)
                    .addComponent(comboBoxSemestreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt10)
                    .addComponent(comboBoxCarreraMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarMateria)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Materia", jPanel2);

        txt11.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt11.setText("ID estudiante");

        outputIdEstudianteMatricula.setEnabled(false);

        txt12.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt12.setText("COD materia");

        outputCodigoMateriaMatricula.setEnabled(false);

        inputPeriodoAcademicoMatricula.setEnabled(false);

        txt13.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt13.setText("Periodo academico");

        txt14.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt14.setText("Nota1");

        txt15.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt15.setText("Nota2");

        txt16.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt16.setText("Nota3");

        btnCargarDatosMatricula.setFont(new java.awt.Font("Ubuntu Sans", 1, 14)); // NOI18N
        btnCargarDatosMatricula.setText("Cargar Datos");
        btnCargarDatosMatricula.addActionListener(this::btnCargarDatosMatriculaActionPerformed);

        btnGuardarInfoMatricula.setFont(new java.awt.Font("Ubuntu Sans", 1, 14)); // NOI18N
        btnGuardarInfoMatricula.setText("Guardar info");
        btnGuardarInfoMatricula.addActionListener(this::btnGuardarInfoMatriculaActionPerformed);

        btnCargarNotasMatricula.setFont(new java.awt.Font("Ubuntu Sans", 1, 14)); // NOI18N
        btnCargarNotasMatricula.setText("Cargar Notas");
        btnCargarNotasMatricula.addActionListener(this::btnCargarNotasMatriculaActionPerformed);

        btnGuardarMatricula.setFont(new java.awt.Font("Ubuntu Sans", 1, 14)); // NOI18N
        btnGuardarMatricula.setText("Guardar");
        btnGuardarMatricula.addActionListener(this::btnGuardarMatriculaActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txt11)
                                .addGap(18, 18, 18)
                                .addComponent(outputIdEstudianteMatricula))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txt12)
                                .addGap(18, 18, 18)
                                .addComponent(outputCodigoMateriaMatricula))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txt13)
                                .addGap(18, 18, 18)
                                .addComponent(inputPeriodoAcademicoMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)))
                        .addGap(254, 254, 254))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txt14)
                                .addGap(18, 18, 18)
                                .addComponent(inputNota1Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt15)
                                .addGap(18, 18, 18)
                                .addComponent(inputNota2Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt16)
                                .addGap(18, 18, 18)
                                .addComponent(inputNota3Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnCargarDatosMatricula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGuardarInfoMatricula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCargarNotasMatricula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGuardarMatricula)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt11)
                    .addComponent(outputIdEstudianteMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt12)
                    .addComponent(outputCodigoMateriaMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt13)
                    .addComponent(inputPeriodoAcademicoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt14)
                    .addComponent(inputNota1Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt15)
                    .addComponent(inputNota2Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt16)
                    .addComponent(inputNota3Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCargarDatosMatricula)
                    .addComponent(btnGuardarInfoMatricula)
                    .addComponent(btnCargarNotasMatricula)
                    .addComponent(btnGuardarMatricula))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Matricula", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 151, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEstudianteActionPerformed
        // TODO add your handling code here:

        int idEstudiante = Integer.parseInt(inputIdEstudiante.getText());
        String nombreEstudiante= String.valueOf(inputNombreEstudiante.getText());
        int indexEdad = comboBoxEdadEstudiante.getSelectedIndex();
        String correo = inputCorreoEstudiante.getText();
        
        
        //para saber que radiobutton se eligió
        String sexoEstudiante = "";
        if (jRadioButton1.isSelected()){
            sexoEstudiante = "masculino";
        } 
        else if (jRadioButton2.isSelected()){
            sexoEstudiante = "femenino";
        }

        
        //para saber la edad por medio del comboBox
        int edadEstudiante = 0;
        switch (indexEdad) {
            case 0:
                JOptionPane.showMessageDialog(rootPane, "Usted no ha seleccionado edad");
                break;
            case 1:
                edadEstudiante = 17;
                break;
            case 2:
                edadEstudiante = 18;
                break;
            case 3:
                edadEstudiante = 19;
                break;
            case 4:
                edadEstudiante = 20;
                break;
            case 5:
                edadEstudiante = 21;
                break;
            case 6:
                edadEstudiante = 22;
                break;
            case 7:
                edadEstudiante = 23;
                break;
            default:
                edadEstudiante = 0;
                break;
        }
        
        estudiante.setCorreo(correo);
        estudiante.setId(idEstudiante);
        estudiante.setEdad(edadEstudiante);
        estudiante.setNombre(nombreEstudiante);
        estudiante.setSexo(sexoEstudiante);
        
        System.out.println(estudiante.getCorreo() + "\n" + 
                estudiante.getEdad() + "\n" + 
                estudiante.getId() + "\n" + 
                estudiante.getNombre() + "\n" + 
                estudiante.getSexo());
        
        
    }//GEN-LAST:event_btnGuardarEstudianteActionPerformed

    private void btnGuardarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarMateriaActionPerformed
        // TODO add your handling code here:
        
        int codMateria = Integer.parseInt(inputCodigoMateria.getText());
        String nombreMateria = String.valueOf(inputNombreMateria.getText());
        int indexNCredito = comboBoxNumeroCreditoMateria.getSelectedIndex();
        int indexSemestre = comboBoxSemestreMateria.getSelectedIndex();
        int indexCarrera = comboBoxCarreraMateria.getSelectedIndex();
        
        int nCreditoMateria = 0;
        switch(indexNCredito){
            case 0:
                JOptionPane.showMessageDialog(rootPane, "Usted no ha seleccionado ninguna cantidad de creditos");
                break;
                
            case 1:
                nCreditoMateria = 1;
                break;
            
            case 2:
                nCreditoMateria = 2;
                break;
            
            case 3:
                nCreditoMateria = 3;
                break;
            
            case 4:
                nCreditoMateria = 4;
                break;
            
            case 5:
                nCreditoMateria = 5;
                break;
            
            case 6:
                nCreditoMateria = 6;
                break;
        }
        
        
        int semestreMateria = 0;
        switch(indexSemestre){
            case 0:
                JOptionPane.showMessageDialog(rootPane, "Usted no ha seleccionado ningun semestre");
                break;
                
            case 1:
                semestreMateria = 1;
                break;
            
            case 2:
                semestreMateria = 2;
                break;
            
            case 3:
                semestreMateria = 3;
                break;
            
            case 4:
                semestreMateria = 4;
                break;
            
            case 5:
                semestreMateria = 5;
                break;
            
            case 6:
                semestreMateria = 6;
                break;
                
            case 7:
                semestreMateria = 7;
                break;
                
            case 8:
                semestreMateria = 8;
                break;
                    
            case 9:
                semestreMateria = 9;
                break;
                    
            case 10:
                semestreMateria = 10;
                break;
        }
        
        
        
        String carreraMateria = "";
        switch(indexCarrera){
            case 0:
                JOptionPane.showMessageDialog(rootPane, "Usted no ha seleccionado ningun semestre");
                break;
                
            case 1:
                carreraMateria = "filosofia";
                break;
            
            case 2:
                carreraMateria = "trabajo social";
                break;
            
            case 3:
                carreraMateria = "diseño grafico";
                break;
        }
        
        materia.setCarrera(carreraMateria);
        materia.setCodigo(codMateria);
        materia.setNombre(nombreMateria);
        materia.setSemestre(semestreMateria);
        materia.setnCreditos(nCreditoMateria);
        
        System.out.println(materia.getCarrera() + "\n" + 
                materia.getCodigo() + "\n" + 
                materia.getNombre() + "\n" + 
                materia.getSemestre() + "\n" + 
                materia.getnCreditos());
        
    }//GEN-LAST:event_btnGuardarMateriaActionPerformed

    private void btnCargarDatosMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarDatosMatriculaActionPerformed
        // TODO add your handling code here:
        
        outputIdEstudianteMatricula.setText(String.valueOf(estudiante.getId()));
        outputCodigoMateriaMatricula.setText(String.valueOf(materia.getCodigo()));
        
        btnGuardarInfoMatricula.setVisible(true);
        inputPeriodoAcademicoMatricula.setEnabled(true);
        
    }//GEN-LAST:event_btnCargarDatosMatriculaActionPerformed

    private void btnGuardarInfoMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarInfoMatriculaActionPerformed
        // TODO add your handling code here:

        int idEstudianteMatricula = Integer.parseInt(outputIdEstudianteMatricula.getText());
        int codMateriaMatricula = Integer.parseInt(outputCodigoMateriaMatricula.getText());
        int periodoMatricula = Integer.parseInt(inputPeriodoAcademicoMatricula.getText());
        
        matricula.setId(idEstudianteMatricula);
        matricula.setCodMateria(codMateriaMatricula);
        matricula.setPeriodoAcademico(periodoMatricula);
        
        txt14.setVisible(true);
        txt15.setVisible(true);
        txt16.setVisible(true);
        
        inputNota1Matricula.setVisible(true);
        inputNota2Matricula.setVisible(true);
        inputNota3Matricula.setVisible(true);
        
        btnCargarNotasMatricula.setVisible(true);
    }//GEN-LAST:event_btnGuardarInfoMatriculaActionPerformed

    private void btnCargarNotasMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarNotasMatriculaActionPerformed
        // TODO add your handling code here:
        
        float nota1Matricula = Float.parseFloat(inputNota1Matricula.getText());
        float nota2Matricula = Float.parseFloat(inputNota2Matricula.getText());
        float nota3Matricula = Float.parseFloat(inputNota3Matricula.getText());
        
        matricula.setNota1(nota1Matricula);
        matricula.setNota2(nota2Matricula);
        matricula.setNota3(nota3Matricula);
        
        btnGuardarMatricula.setVisible(true);
        
    }//GEN-LAST:event_btnCargarNotasMatriculaActionPerformed

    private void btnGuardarMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarMatriculaActionPerformed
        // TODO add your handling code here:
        
        int idEstudianteMatricula = Integer.parseInt(outputIdEstudianteMatricula.getText());
        int codMateriaMatricula = Integer.parseInt(outputCodigoMateriaMatricula.getText());
        int periodoMatricula = Integer.parseInt(inputPeriodoAcademicoMatricula.getText());
        
        float nota1Matricula = Float.parseFloat(inputNota1Matricula.getText());
        float nota2Matricula = Float.parseFloat(inputNota2Matricula.getText());
        float nota3Matricula = Float.parseFloat(inputNota3Matricula.getText());
        
        matricula.setId(idEstudianteMatricula);
        matricula.setCodMateria(codMateriaMatricula);
        matricula.setPeriodoAcademico(periodoMatricula);
        
        matricula.setNota1(nota1Matricula);
        matricula.setNota2(nota2Matricula);
        matricula.setNota3(nota3Matricula);
        
    }//GEN-LAST:event_btnGuardarMatriculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new vista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarDatosMatricula;
    private javax.swing.JButton btnCargarNotasMatricula;
    private javax.swing.JButton btnGuardarEstudiante;
    private javax.swing.JButton btnGuardarInfoMatricula;
    private javax.swing.JButton btnGuardarMateria;
    private javax.swing.JButton btnGuardarMatricula;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboBoxCarreraMateria;
    private javax.swing.JComboBox<String> comboBoxEdadEstudiante;
    private javax.swing.JComboBox<String> comboBoxNumeroCreditoMateria;
    private javax.swing.JComboBox<String> comboBoxSemestreMateria;
    private javax.swing.JTextField inputCodigoMateria;
    private javax.swing.JTextField inputCorreoEstudiante;
    private javax.swing.JTextField inputIdEstudiante;
    private javax.swing.JTextField inputNombreEstudiante;
    private javax.swing.JTextField inputNombreMateria;
    private javax.swing.JTextField inputNota1Matricula;
    private javax.swing.JTextField inputNota2Matricula;
    private javax.swing.JTextField inputNota3Matricula;
    private javax.swing.JTextField inputPeriodoAcademicoMatricula;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField outputCodigoMateriaMatricula;
    private javax.swing.JTextField outputIdEstudianteMatricula;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt10;
    private javax.swing.JLabel txt11;
    private javax.swing.JLabel txt12;
    private javax.swing.JLabel txt13;
    private javax.swing.JLabel txt14;
    private javax.swing.JLabel txt15;
    private javax.swing.JLabel txt16;
    private javax.swing.JLabel txt2;
    private javax.swing.JLabel txt3;
    private javax.swing.JLabel txt4;
    private javax.swing.JLabel txt5;
    private javax.swing.JLabel txt6;
    private javax.swing.JLabel txt7;
    private javax.swing.JLabel txt8;
    private javax.swing.JLabel txt9;
    // End of variables declaration//GEN-END:variables
}
