package piscinas;
public class vista extends javax.swing.JFrame {
    CalculadoraPiscina coneccion = new CalculadoraPiscina();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(vista.class.getName());

    /**
     * Creates new form vista
     */
    public vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        txt1 = new javax.swing.JLabel();
        txt2 = new javax.swing.JLabel();
        txt3 = new javax.swing.JLabel();
        txt4 = new javax.swing.JLabel();
        txt5 = new javax.swing.JLabel();
        txt6 = new javax.swing.JLabel();
        txt7 = new javax.swing.JLabel();
        txt8 = new javax.swing.JLabel();
        inputProfundidad = new javax.swing.JTextField();
        inputLargo = new javax.swing.JTextField();
        inputMetroCubicoExcavacion = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        inputAncho = new javax.swing.JTextField();
        inputMetroCuadradoPared = new javax.swing.JTextField();
        inputMetroCuadradoEnchape = new javax.swing.JTextField();
        inputMetroCuadradoPiso = new javax.swing.JTextField();
        txt9 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        bg2 = new javax.swing.JPanel();
        txt10 = new javax.swing.JLabel();
        outputMetrosParedesLargo = new javax.swing.JTextField();
        txt11 = new javax.swing.JLabel();
        outputMetrosParedesAncho = new javax.swing.JTextField();
        txt12 = new javax.swing.JLabel();
        outputMetrosPiso = new javax.swing.JTextField();
        outputEnchapes = new javax.swing.JTextField();
        txt13 = new javax.swing.JLabel();
        outputVolumenAgua = new javax.swing.JTextField();
        txt14 = new javax.swing.JLabel();
        outputCostosParedes = new javax.swing.JTextField();
        txt15 = new javax.swing.JLabel();
        outputCostosPisos = new javax.swing.JTextField();
        txt16 = new javax.swing.JLabel();
        outputCostosExcavacion = new javax.swing.JTextField();
        txt17 = new javax.swing.JLabel();
        outputCostosEnchape = new javax.swing.JTextField();
        txt18 = new javax.swing.JLabel();
        txt19 = new javax.swing.JLabel();
        outputCostosAgua = new javax.swing.JTextField();
        outputCostosQuimicos = new javax.swing.JTextField();
        txt20 = new javax.swing.JLabel();
        txt21 = new javax.swing.JLabel();
        outputCostoTotal = new javax.swing.JTextField();
        txt22 = new javax.swing.JLabel();
        outputMetrosCubicos = new javax.swing.JTextField();
        btnMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt1.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt1.setText("Calculadora costos de piscina");

        txt2.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt2.setText("Largo:");

        txt3.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt3.setText("Ancho:");

        txt4.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt4.setText("Profundidad:");

        txt5.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt5.setText("Metro cúbico de excavación");

        txt6.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt6.setText("Metro cuadrado de concreto para paredes");

        txt7.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt7.setText("Metro cuadrado de enchape");

        txt8.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt8.setText("Metro cuadrado de concreto para piso");

        inputProfundidad.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N

        inputLargo.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N

        inputMetroCubicoExcavacion.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N

        inputAncho.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N

        inputMetroCuadradoPared.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N

        inputMetroCuadradoEnchape.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N

        inputMetroCuadradoPiso.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N

        txt9.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt9.setText("Precios");

        btnGuardar.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        bg2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txt10.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt10.setText("Metros paredes largo");

        outputMetrosParedesLargo.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N

        txt11.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt11.setText("Metros paredes ancho");

        outputMetrosParedesAncho.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N

        txt12.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt12.setText("Metros Piso");

        outputMetrosPiso.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N

        outputEnchapes.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N

        txt13.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt13.setText("Enchapes");

        outputVolumenAgua.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N

        txt14.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt14.setText("Volumen agua");

        outputCostosParedes.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N

        txt15.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt15.setText("Costos paredes");

        outputCostosPisos.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N

        txt16.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt16.setText("costos Pisos");

        outputCostosExcavacion.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N

        txt17.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt17.setText("costos excavacion");

        outputCostosEnchape.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N

        txt18.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt18.setText("costos enchape");

        txt19.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt19.setText("costos agua");

        outputCostosAgua.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N

        outputCostosQuimicos.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N

        txt20.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt20.setText("costos quimicos");

        txt21.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt21.setText("Costo total de la piscina");

        outputCostoTotal.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N

        txt22.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt22.setText("Metros Cubicos");

        outputMetrosCubicos.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N

        javax.swing.GroupLayout bg2Layout = new javax.swing.GroupLayout(bg2);
        bg2.setLayout(bg2Layout);
        bg2Layout.setHorizontalGroup(
            bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outputMetrosParedesLargo)
                    .addComponent(txt11, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                    .addComponent(outputMetrosParedesAncho)
                    .addComponent(txt12, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                    .addComponent(outputMetrosPiso)
                    .addComponent(outputEnchapes)
                    .addComponent(txt13, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                    .addComponent(outputVolumenAgua)
                    .addComponent(txt14, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                    .addComponent(outputCostosParedes)
                    .addComponent(txt15, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                    .addComponent(outputCostosPisos)
                    .addComponent(txt16, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                    .addComponent(outputCostosExcavacion)
                    .addComponent(txt17, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                    .addComponent(outputCostosEnchape)
                    .addComponent(txt18, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                    .addComponent(txt19, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                    .addComponent(outputCostosAgua)
                    .addComponent(outputCostosQuimicos)
                    .addComponent(txt20, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                    .addComponent(txt21, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                    .addComponent(outputCostoTotal)
                    .addComponent(txt22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outputMetrosCubicos))
                .addContainerGap())
        );
        bg2Layout.setVerticalGroup(
            bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg2Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(txt22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputMetrosCubicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputMetrosParedesLargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputMetrosParedesAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputMetrosPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputEnchapes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputVolumenAgua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputCostosParedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputCostosPisos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputCostosExcavacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputCostosEnchape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputCostosAgua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputCostosQuimicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputCostoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnMostrar.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(this::btnMostrarActionPerformed);

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1)
                                    .addComponent(txt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(txt2))
                                    .addComponent(inputLargo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt3)
                                .addGap(137, 137, 137)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt4)
                                    .addComponent(inputProfundidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)))
                        .addGap(2, 2, 2))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addGap(141, 141, 141)
                                        .addComponent(txt9)
                                        .addGap(157, 157, 157))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(inputMetroCuadradoPared, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt6))
                                        .addGroup(bgLayout.createSequentialGroup()
                                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(inputMetroCuadradoPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createSequentialGroup()
                                                        .addGap(21, 21, 21)
                                                        .addComponent(txt8)))
                                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(inputMetroCuadradoEnchape, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(bgLayout.createSequentialGroup()
                                                            .addGap(43, 43, 43)
                                                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(inputMetroCubicoExcavacion, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(txt5)))
                                                        .addGroup(bgLayout.createSequentialGroup()
                                                            .addGap(54, 54, 54)
                                                            .addComponent(txt7)))))
                                            .addGap(13, 13, 13)))))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(btnGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(btnMostrar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)))
                .addComponent(bg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bgLayout.createSequentialGroup()
                    .addGap(251, 251, 251)
                    .addComponent(inputAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(279, Short.MAX_VALUE)))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt1)
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt2)
                    .addComponent(txt3)
                    .addComponent(txt4))
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputProfundidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputLargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputMetroCubicoExcavacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputMetroCuadradoPared, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputMetroCuadradoPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputMetroCuadradoEnchape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnMostrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(bg2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bgLayout.createSequentialGroup()
                    .addGap(96, 96, 96)
                    .addComponent(inputAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(707, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
        //se toman las variables
        int largo = Integer.parseInt(inputLargo.getText());
        int ancho = Integer.parseInt(inputAncho.getText());
        int profundidad = Integer.parseInt(inputProfundidad.getText());

        float metroCubicoExcavacion = Float.parseFloat(inputMetroCubicoExcavacion.getText());
        float metroCuadradoPared = Float.parseFloat(inputMetroCuadradoPared.getText());
        float metroCuadradoPiso = Float.parseFloat(inputMetroCuadradoPiso.getText());
        float metroCuadradoEnchape = Float.parseFloat(inputMetroCuadradoEnchape.getText());
  
        //se envían al metodo
        coneccion.SetAncho(ancho);
        coneccion.SetLargo(largo);
        coneccion.SetProfundidad(profundidad);
        
        coneccion.SetPrecioMEnchape(metroCuadradoEnchape);
        coneccion.SetPrecioMExcavacion(metroCubicoExcavacion);
        coneccion.SetPrecioMconcretoParedes(metroCuadradoPared);
        coneccion.SetPrecioMconcretoPisos(metroCuadradoPiso);
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        
        outputMetrosCubicos.setText(String.valueOf(coneccion.CalcularMtsCubicos()));
        outputMetrosParedesLargo.setText(String.valueOf(coneccion.CalcularMtsParedesLargo()));
        outputMetrosParedesAncho.setText(String.valueOf(coneccion.CalcularMtsParedesAncho()));
        outputMetrosPiso.setText(String.valueOf(coneccion.CalcularMtsPisos()));
        outputEnchapes.setText(String.valueOf(coneccion.CalcularEnchapes()));
        outputVolumenAgua.setText(String.valueOf(coneccion.CalcularVolumenAgua()));
        outputCostosParedes.setText(String.valueOf(coneccion.CalcularCostosParedes()));
        outputCostosPisos.setText(String.valueOf(coneccion.CalcularCostosPisos()));
        outputCostosExcavacion.setText(String.valueOf(coneccion.CalcularCostosExcavacion()));
        outputCostosEnchape.setText(String.valueOf(coneccion.CalcularCostosEnchape()));
        outputCostosAgua.setText(String.valueOf(coneccion.CalcularcostoAgua()));
        outputCostosQuimicos.setText(String.valueOf(coneccion.CalcularCostosQuimicos()));
        
        outputCostoTotal.setText(String.valueOf(coneccion.TotalCostoPiscina()));
        
        //debbuging enchape
        System.out.println("calcular mts pisos: " + coneccion.CalcularMtsPisos());
        System.out.println("calcular mts paredes largo: " + coneccion.CalcularMtsParedesLargo());
        System.out.println("calcular mts paredes ancho: " + coneccion.CalcularMtsParedesAncho());
        System.out.println("precio me enchape: " + coneccion.GetPrecioMEnchape());
        
        
    }//GEN-LAST:event_btnMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new vista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bg2;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JTextField inputAncho;
    private javax.swing.JTextField inputLargo;
    private javax.swing.JTextField inputMetroCuadradoEnchape;
    private javax.swing.JTextField inputMetroCuadradoPared;
    private javax.swing.JTextField inputMetroCuadradoPiso;
    private javax.swing.JTextField inputMetroCubicoExcavacion;
    private javax.swing.JTextField inputProfundidad;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField outputCostoTotal;
    private javax.swing.JTextField outputCostosAgua;
    private javax.swing.JTextField outputCostosEnchape;
    private javax.swing.JTextField outputCostosExcavacion;
    private javax.swing.JTextField outputCostosParedes;
    private javax.swing.JTextField outputCostosPisos;
    private javax.swing.JTextField outputCostosQuimicos;
    private javax.swing.JTextField outputEnchapes;
    private javax.swing.JTextField outputMetrosCubicos;
    private javax.swing.JTextField outputMetrosParedesAncho;
    private javax.swing.JTextField outputMetrosParedesLargo;
    private javax.swing.JTextField outputMetrosPiso;
    private javax.swing.JTextField outputVolumenAgua;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt10;
    private javax.swing.JLabel txt11;
    private javax.swing.JLabel txt12;
    private javax.swing.JLabel txt13;
    private javax.swing.JLabel txt14;
    private javax.swing.JLabel txt15;
    private javax.swing.JLabel txt16;
    private javax.swing.JLabel txt17;
    private javax.swing.JLabel txt18;
    private javax.swing.JLabel txt19;
    private javax.swing.JLabel txt2;
    private javax.swing.JLabel txt20;
    private javax.swing.JLabel txt21;
    private javax.swing.JLabel txt22;
    private javax.swing.JLabel txt3;
    private javax.swing.JLabel txt4;
    private javax.swing.JLabel txt5;
    private javax.swing.JLabel txt6;
    private javax.swing.JLabel txt7;
    private javax.swing.JLabel txt8;
    private javax.swing.JLabel txt9;
    // End of variables declaration//GEN-END:variables
}
