/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tienda;

import java.text.SimpleDateFormat;
//import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author aser
 */
public class vista1 extends javax.swing.JFrame {
    
    inventario instancia = new inventario(5);
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(vista1.class.getName());

    /**
     * Creates new form vista1
     */
    public vista1() {
        initComponents();
        inputProductoCodigo.setText(String.valueOf(codProducto));
        inputFacturaIdFactura.setText(String.valueOf(contNFactura));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        bgProducto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inputProductoCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        inputProductoDescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputProductoCantidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputProductoValor = new javax.swing.JTextField();
        btnProductoGuardar = new javax.swing.JButton();
        bgCliente = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        inputClienteId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        inputClienteNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        inputClienteDireccion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        inputClienteTelefono = new javax.swing.JTextField();
        btnClienteGuardar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        inputClienteSexo = new javax.swing.JTextField();
        bgFactura = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        inputFacturaIdFactura = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        outputFacturaNombre = new javax.swing.JTextField();
        jCalendar = new com.toedter.calendar.JCalendar();
        comboFacturaIdCliente = new javax.swing.JComboBox<>();
        btnFacturaGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu Sans", 1, 26)); // NOI18N
        jLabel1.setText("Codigo");

        inputProductoCodigo.setFont(new java.awt.Font("Ubuntu Sans", 1, 26)); // NOI18N
        inputProductoCodigo.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Ubuntu Sans", 1, 26)); // NOI18N
        jLabel2.setText("Descripción");

        inputProductoDescripcion.setFont(new java.awt.Font("Ubuntu Sans", 1, 26)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Ubuntu Sans", 1, 26)); // NOI18N
        jLabel3.setText("Cantidad");

        inputProductoCantidad.setFont(new java.awt.Font("Ubuntu Sans", 1, 26)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Ubuntu Sans", 1, 26)); // NOI18N
        jLabel4.setText("Valor");

        inputProductoValor.setFont(new java.awt.Font("Ubuntu Sans", 1, 26)); // NOI18N

        btnProductoGuardar.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        btnProductoGuardar.setText("Guardar");
        btnProductoGuardar.addActionListener(this::btnProductoGuardarActionPerformed);

        javax.swing.GroupLayout bgProductoLayout = new javax.swing.GroupLayout(bgProducto);
        bgProducto.setLayout(bgProductoLayout);
        bgProductoLayout.setHorizontalGroup(
            bgProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgProductoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputProductoCantidad))
                    .addGroup(bgProductoLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(inputProductoValor))
                    .addGroup(bgProductoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputProductoCodigo))
                    .addGroup(bgProductoLayout.createSequentialGroup()
                        .addGroup(bgProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(btnProductoGuardar))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(bgProductoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputProductoDescripcion)))
                .addGap(375, 375, 375))
        );
        bgProductoLayout.setVerticalGroup(
            bgProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inputProductoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputProductoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inputProductoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputProductoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProductoGuardar)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Producto", bgProducto);

        jLabel5.setFont(new java.awt.Font("Ubuntu Sans", 1, 26)); // NOI18N
        jLabel5.setText("ID");

        inputClienteId.setFont(new java.awt.Font("Ubuntu Sans", 1, 26)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Ubuntu Sans", 1, 26)); // NOI18N
        jLabel6.setText("Nombre");

        inputClienteNombre.setFont(new java.awt.Font("Ubuntu Sans", 1, 26)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Ubuntu Sans", 1, 26)); // NOI18N
        jLabel7.setText("Direccion");

        inputClienteDireccion.setFont(new java.awt.Font("Ubuntu Sans", 1, 26)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Ubuntu Sans", 1, 26)); // NOI18N
        jLabel8.setText("Telefono");

        inputClienteTelefono.setFont(new java.awt.Font("Ubuntu Sans", 1, 26)); // NOI18N

        btnClienteGuardar.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        btnClienteGuardar.setText("Guardar");
        btnClienteGuardar.addActionListener(this::btnClienteGuardarActionPerformed);

        jLabel9.setFont(new java.awt.Font("Ubuntu Sans", 1, 26)); // NOI18N
        jLabel9.setText("Sexo");

        inputClienteSexo.setFont(new java.awt.Font("Ubuntu Sans", 1, 26)); // NOI18N

        javax.swing.GroupLayout bgClienteLayout = new javax.swing.GroupLayout(bgCliente);
        bgCliente.setLayout(bgClienteLayout);
        bgClienteLayout.setHorizontalGroup(
            bgClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgClienteLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputClienteDireccion))
                    .addGroup(bgClienteLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputClienteId))
                    .addGroup(bgClienteLayout.createSequentialGroup()
                        .addComponent(btnClienteGuardar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(bgClienteLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputClienteNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                    .addGroup(bgClienteLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputClienteTelefono))
                    .addGroup(bgClienteLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputClienteSexo)))
                .addGap(330, 330, 330))
        );
        bgClienteLayout.setVerticalGroup(
            bgClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inputClienteId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(inputClienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(inputClienteDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputClienteTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputClienteSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClienteGuardar)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cliente", bgCliente);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        jLabel10.setText("Nro Factura");

        inputFacturaIdFactura.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        inputFacturaIdFactura.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        jLabel11.setText("idCliente");

        jLabel12.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        jLabel12.setText("Fecha");

        jLabel13.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        jLabel13.setText("nombre");

        outputFacturaNombre.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        outputFacturaNombre.setEnabled(false);

        comboFacturaIdCliente.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                comboFacturaIdClienteInputMethodTextChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputFacturaIdFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboFacturaIdCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(outputFacturaNombre)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCalendar, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel12)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(inputFacturaIdFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(comboFacturaIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(outputFacturaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jCalendar, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnFacturaGuardar.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        btnFacturaGuardar.setText("Guardar");
        btnFacturaGuardar.addActionListener(this::btnFacturaGuardarActionPerformed);

        javax.swing.GroupLayout bgFacturaLayout = new javax.swing.GroupLayout(bgFactura);
        bgFactura.setLayout(bgFacturaLayout);
        bgFacturaLayout.setHorizontalGroup(
            bgFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgFacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bgFacturaLayout.createSequentialGroup()
                        .addComponent(btnFacturaGuardar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        bgFacturaLayout.setVerticalGroup(
            bgFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgFacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFacturaGuardar)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Factura", bgFactura);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int contProducto = 0;
    int codProducto = 1;
    private void btnProductoGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoGuardarActionPerformed

        // TODO add your handling code here:        
        //  setter de datos Producto, junto con validaciones
        
        if (inputProductoDescripcion.getText().isEmpty() ||
                inputProductoCantidad.getText().isEmpty() ||
                inputProductoValor.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Debe llenar todos los campos");
        } else{
            
            if (contProducto  < instancia.getTam()){
                
//                inputProductoCodigo.setText(String.valueOf(codProducto));
                String descripcion = inputProductoDescripcion.getText();
                int cantidad = Integer.parseInt(inputProductoCantidad.getText());
                int valor = Integer.parseInt(inputProductoValor.getText());
                
                instancia.setDatosProducto(contProducto, String.valueOf(codProducto), descripcion, cantidad, valor);
                contProducto++;
                codProducto++;
                JOptionPane.showMessageDialog(rootPane, "Producto ingresado exitosamente");
            } else{
                JOptionPane.showMessageDialog(rootPane, "El arreglo está lleno");
            }
        }
        
    }//GEN-LAST:event_btnProductoGuardarActionPerformed

    int contCliente = 0;
    private void btnClienteGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteGuardarActionPerformed
        // TODO add your handling code here:
        //setter datos Cliente
        
        //campos llenos
        if (inputClienteDireccion.getText().isEmpty()||
                inputClienteId.getText().isEmpty()||
                inputClienteNombre.getText().isEmpty()||
                inputClienteSexo.getText().isEmpty()||
                inputClienteTelefono.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(rootPane, "Debe llenar todos los campos");
        } else{
            //espacio en array
            if (contCliente < instancia.getTam()){
                
                String direccion = inputClienteDireccion.getText();
                String id = inputClienteId.getText();
                String nombre = inputClienteNombre.getText();
                String sexo = inputClienteSexo.getText();
                String telefono = inputClienteTelefono.getText();
                
                int tam = instancia.getTam();
                
                //id ya existente
                for (int i = 0; i < tam; i++){
                    if (instancia.getIdCliente(i, id).equals(id)) {
                        JOptionPane.showMessageDialog(rootPane, "Este ID ya ha sido ingresado");
                        return;
                    }
                }
                
                instancia.setDatosCliente(contCliente, direccion, id, nombre, sexo, telefono);
                contCliente++;
                JOptionPane.showMessageDialog(rootPane, "Cliente ingresado exitosamente");
                
                comboFacturaIdCliente.addItem(id);
            
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "El arreglo está lleno");
            }
        }
        
    }//GEN-LAST:event_btnClienteGuardarActionPerformed

    int contFactura = 0;
    int contNFactura = 1;
    private void btnFacturaGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturaGuardarActionPerformed
        // TODO add your handling code here:

//        String id = comboFacturaIdCliente.getItemAt(0);
        
        if (jCalendar.getDate() != null) {
            //se crea el formato de fecha
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            //se aplica el formato al tomar los datos
            String fecha = formato.format(jCalendar.getDate());
            
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecciona una fecha");
        }
        
    }//GEN-LAST:event_btnFacturaGuardarActionPerformed

    private void comboFacturaIdClienteInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_comboFacturaIdClienteInputMethodTextChanged
        // TODO add your handling code here:
        int indexElegido = comboFacturaIdCliente.getSelectedIndex();
        System.out.println("elegido: " + indexElegido);
    }//GEN-LAST:event_comboFacturaIdClienteInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new vista1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgCliente;
    private javax.swing.JPanel bgFactura;
    private javax.swing.JPanel bgProducto;
    private javax.swing.JButton btnClienteGuardar;
    private javax.swing.JButton btnFacturaGuardar;
    private javax.swing.JButton btnProductoGuardar;
    private javax.swing.JComboBox<String> comboFacturaIdCliente;
    private javax.swing.JTextField inputClienteDireccion;
    private javax.swing.JTextField inputClienteId;
    private javax.swing.JTextField inputClienteNombre;
    private javax.swing.JTextField inputClienteSexo;
    private javax.swing.JTextField inputClienteTelefono;
    private javax.swing.JTextField inputFacturaIdFactura;
    private javax.swing.JTextField inputProductoCantidad;
    private javax.swing.JTextField inputProductoCodigo;
    private javax.swing.JTextField inputProductoDescripcion;
    private javax.swing.JTextField inputProductoValor;
    private com.toedter.calendar.JCalendar jCalendar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField outputFacturaNombre;
    // End of variables declaration//GEN-END:variables
}
