/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minominaempleado;

/**
 *
 * @author aser
 */
public class vista extends javax.swing.JFrame {
    modelo interaccion = new modelo();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(vista.class.getName());

    /**
     * Creates new form vista
     */
    public vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        txt1 = new javax.swing.JLabel();
        txt2 = new javax.swing.JLabel();
        inputHorasTrabajadas = new javax.swing.JTextField();
        txt3 = new javax.swing.JLabel();
        outputSalarioMinimo = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        txt4 = new javax.swing.JLabel();
        inputPrecioHora = new javax.swing.JTextField();
        txt5 = new javax.swing.JLabel();
        outputSalarioNeto = new javax.swing.JTextField();
        txt6 = new javax.swing.JLabel();
        outputHorasExtra = new javax.swing.JTextField();
        txt7 = new javax.swing.JLabel();
        outputRetencion = new javax.swing.JTextField();
        txt8 = new javax.swing.JLabel();
        outputNominaTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt1.setFont(new java.awt.Font("Ubuntu Sans", 1, 24)); // NOI18N
        txt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt1.setText("Calculadora de nómina de empleado");
        txt1.setToolTipText("");

        txt2.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt2.setText("Número de horas trabajadas");
        txt2.setToolTipText("");

        inputHorasTrabajadas.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        inputHorasTrabajadas.addActionListener(this::inputHorasTrabajadasActionPerformed);

        txt3.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt3.setText("Salario minimo");
        txt3.setToolTipText("");

        outputSalarioMinimo.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        outputSalarioMinimo.setEnabled(false);

        btnGuardar.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnMostrar.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(this::btnMostrarActionPerformed);

        txt4.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt4.setText("Precio de la hora trabajada");
        txt4.setToolTipText("");

        inputPrecioHora.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N

        txt5.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt5.setText("Salario neto");
        txt5.setToolTipText("");

        outputSalarioNeto.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        outputSalarioNeto.setEnabled(false);

        txt6.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt6.setText("Horas extra");
        txt6.setToolTipText("");

        outputHorasExtra.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        outputHorasExtra.setEnabled(false);

        txt7.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt7.setText("Retención");
        txt7.setToolTipText("");

        outputRetencion.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        outputRetencion.setEnabled(false);

        txt8.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        txt8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt8.setText("Nómina total");
        txt8.setToolTipText("");

        outputNominaTotal.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        outputNominaTotal.setEnabled(false);

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnMostrar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(txt2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputHorasTrabajadas))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(txt3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(outputSalarioMinimo))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(txt5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(outputSalarioNeto))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(txt6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(outputHorasExtra))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(txt7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(outputRetencion))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(txt8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(outputNominaTotal))))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputPrecioHora)))
                .addContainerGap())
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt2)
                    .addComponent(inputHorasTrabajadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt4)
                    .addComponent(inputPrecioHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnMostrar))
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt3)
                    .addComponent(outputSalarioMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt5)
                    .addComponent(outputSalarioNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt6)
                    .addComponent(outputHorasExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt7)
                    .addComponent(outputRetencion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt8)
                    .addComponent(outputNominaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputHorasTrabajadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputHorasTrabajadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputHorasTrabajadasActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        outputSalarioMinimo.setText(String.valueOf(interaccion.getSm()) + "$");
        outputHorasExtra.setText(String.valueOf(interaccion.cuantasHorasExtra()));
        outputRetencion.setText(String.valueOf(interaccion.cuantaRetencion()) + "$");
        outputSalarioNeto.setText(String.valueOf(interaccion.cuantoNeto()) + "$");
        outputNominaTotal.setText(String.valueOf(interaccion.cuantaNominaTotal()) + "$");
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        float horasTrabajadas = Float.valueOf(inputHorasTrabajadas.getText());
        float precioHoras = Float.valueOf(inputPrecioHora.getText());
        
        interaccion.setHorasTrabajadas(horasTrabajadas);
        interaccion.setPrecioHora(precioHoras);
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new vista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JTextField inputHorasTrabajadas;
    private javax.swing.JTextField inputPrecioHora;
    private javax.swing.JTextField outputHorasExtra;
    private javax.swing.JTextField outputNominaTotal;
    private javax.swing.JTextField outputRetencion;
    private javax.swing.JTextField outputSalarioMinimo;
    private javax.swing.JTextField outputSalarioNeto;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt2;
    private javax.swing.JLabel txt3;
    private javax.swing.JLabel txt4;
    private javax.swing.JLabel txt5;
    private javax.swing.JLabel txt6;
    private javax.swing.JLabel txt7;
    private javax.swing.JLabel txt8;
    // End of variables declaration//GEN-END:variables
}
